// Auto-generated by apps/web/scripts/generate-plugin-registry.mjs
// Do not edit manually.
import type { PluginPackageManifest } from "@curolia/plugin-contract";

import { pluginManifest as pluginManifest0 } from "@curolia/plugin-google-photos";
import { pluginManifest as pluginManifest1 } from "@curolia/plugin-ical";

export const installedPluginManifests: PluginPackageManifest[] = [
  pluginManifest0,
  pluginManifest1,
];
