/** @generated by packages/supabase/scripts/extract-plugin-oauth-registry.ts — do not edit */
/** Source: contributions.oauth in each plugin's pluginManifest (export from src/index.ts). */

/** Scopes prepended to each plugin's declared scopes for a given OAuth provider id. */
export const OAUTH_COMPANION_SCOPES_BY_PROVIDER: Record<
  string,
  readonly string[]
> = {
  google: ["openid", "email", "profile"],
};

/** pluginTypeId → provider id → resource/API scopes (excludes companion scopes). */
const PLUGIN_OAUTH_SCOPES_BY_PROVIDER: Record<
  string,
  Record<string, readonly string[]>
> = {
  google_photos: {
    google: [
      "https://www.googleapis.com/auth/photospicker.mediaitems.readonly",
    ],
  },
};

export function pluginOAuthScopesFor(
  pluginTypeId: string,
  providerId: string,
): readonly string[] | undefined {
  return PLUGIN_OAUTH_SCOPES_BY_PROVIDER[pluginTypeId]?.[providerId];
}

/** Space-separated scope string for the provider's authorize endpoint. */
export function authorizeScopesSpaceSeparated(
  pluginTypeId: string,
  providerId: string,
): string {
  const pluginScopes = pluginOAuthScopesFor(pluginTypeId, providerId);
  if (!pluginScopes?.length) {
    throw new Error(
      "plugin-oauth: no OAuth scopes registered for plugin " +
        pluginTypeId +
        " provider " +
        providerId,
    );
  }
  const companion = OAUTH_COMPANION_SCOPES_BY_PROVIDER[providerId] ?? [];
  return [...companion, ...pluginScopes].join(" ");
}
