/**
 * Collects OAuth scopes from each plugin package's exported `pluginManifest`
 * (`src/index.ts`) and generates `scopes-registry.gen.ts` for the plugin-oauth
 * Edge function.
 *
 * Run via `tsx` from the repo root (see `sync-plugins.mjs`).
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import type { PluginPackageManifest } from "../../plugin-contract/src/index.ts";
import { OAUTH_COMPANION_SCOPES_BY_PROVIDER } from "../../plugins/oauth/src/oauth-companion-scopes.ts";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
/** Repository root (`curolia-v2/`) — `scripts/` → .. → .. → repo */
const repoRoot = path.resolve(__dirname, "../../..");
const pluginsRoot = path.join(repoRoot, "packages", "plugins");
const registryOutPath = path.join(
  pluginsRoot,
  "oauth",
  "supabase",
  "functions",
  "plugin-oauth",
  "scopes-registry.gen.ts",
);

type ByPluginMap = Map<string, Map<string, Set<string>>>;

async function collectFromManifests(): Promise<ByPluginMap> {
  const byPlugin: ByPluginMap = new Map();

  for (const ent of fs.readdirSync(pluginsRoot, { withFileTypes: true })) {
    if (!ent.isDirectory()) continue;
    const pkgDir = path.join(pluginsRoot, ent.name);
    const indexTs = path.join(pkgDir, "src", "index.ts");
    if (!fs.existsSync(indexTs)) continue;

    let mod: { pluginManifest?: PluginPackageManifest };
    try {
      mod = await import(pathToFileURL(indexTs).href);
    } catch (e) {
      console.warn(
        `extract-plugin-oauth-registry: skipping ${path.relative(repoRoot, indexTs)} (import failed)`,
      );
      continue;
    }

    const manifest = mod.pluginManifest;
    const oauthDecls = manifest?.contributions?.oauth;
    if (!manifest?.id || !oauthDecls?.length) continue;

    for (const dec of oauthDecls) {
      const providerId = dec.provider.trim();
      if (!providerId) {
        throw new Error(
          `extract-plugin-oauth-registry: plugin "${manifest.id}" has empty oauth provider`,
        );
      }

      const companion = new Set(
        OAUTH_COMPANION_SCOPES_BY_PROVIDER[providerId] ?? [],
      );

      const resourceScopes = [...dec.scopes].filter(
        (s) => typeof s === "string" && s.trim() && !companion.has(s),
      );

      if (resourceScopes.length === 0) {
        throw new Error(
          `extract-plugin-oauth-registry: plugin "${manifest.id}" provider "${providerId}": manifest has no scopes beyond companion (${path.relative(repoRoot, indexTs)})`,
        );
      }

      if (!byPlugin.has(manifest.id)) {
        byPlugin.set(manifest.id, new Map());
      }
      const provMap = byPlugin.get(manifest.id)!;
      if (!provMap.has(providerId)) {
        provMap.set(providerId, new Set());
      }
      const bucket = provMap.get(providerId)!;
      for (const s of resourceScopes) bucket.add(s);
    }
  }

  return byPlugin;
}

function emitCompanionLines(): string[] {
  const lines: string[] = [
    `/** Scopes prepended to each plugin's declared scopes for a given OAuth provider id. */`,
    `export const OAUTH_COMPANION_SCOPES_BY_PROVIDER: Record<string, readonly string[]> = {`,
  ];
  const provKeys = Object.keys(OAUTH_COMPANION_SCOPES_BY_PROVIDER).sort();
  for (const prov of provKeys) {
    const scopes = [
      ...(
        OAUTH_COMPANION_SCOPES_BY_PROVIDER as Record<string, readonly string[]>
      )[prov],
    ];
    lines.push(`  "${prov}": [`);
    for (const s of scopes) lines.push(`    "${String(s)}",`);
    lines.push(`  ],`);
  }
  lines.push(`};`, ``);
  return lines;
}

function emitRegistry(byPlugin: ByPluginMap): void {
  const lines = [
    `/** @generated by packages/supabase/scripts/extract-plugin-oauth-registry.ts — do not edit */`,
    `/** Source: contributions.oauth in each plugin's pluginManifest (export from src/index.ts). */`,
    ``,
    ...emitCompanionLines(),
    `/** pluginTypeId → provider id → resource/API scopes (excludes companion scopes). */`,
    `const PLUGIN_OAUTH_SCOPES_BY_PROVIDER: Record<string, Record<string, readonly string[]>> = {`,
  ];

  const pluginIds = [...byPlugin.keys()].sort();
  for (const pid of pluginIds) {
    const pmap = byPlugin.get(pid)!;
    lines.push(`  "${pid}": {`);
    for (const prov of [...pmap.keys()].sort()) {
      const scopes = [...pmap.get(prov)!].sort();
      lines.push(`    "${prov}": [`);
      for (const s of scopes) lines.push(`      "${s}",`);
      lines.push(`    ],`);
    }
    lines.push(`  },`);
  }
  lines.push(`};`);
  lines.push(``);
  lines.push(`export function pluginOAuthScopesFor(`);
  lines.push(`  pluginTypeId: string,`);
  lines.push(`  providerId: string,`);
  lines.push(`): readonly string[] | undefined {`);
  lines.push(
    `  return PLUGIN_OAUTH_SCOPES_BY_PROVIDER[pluginTypeId]?.[providerId];`,
  );
  lines.push(`}`);
  lines.push(``);
  lines.push(
    `/** Space-separated scope string for the provider's authorize endpoint. */`,
  );
  lines.push(`export function authorizeScopesSpaceSeparated(`);
  lines.push(`  pluginTypeId: string,`);
  lines.push(`  providerId: string,`);
  lines.push(`): string {`);
  lines.push(
    `  const pluginScopes = pluginOAuthScopesFor(pluginTypeId, providerId);`,
  );
  lines.push(`  if (!pluginScopes?.length) {`);
  lines.push(`    throw new Error(`);
  lines.push(
    `      "plugin-oauth: no OAuth scopes registered for plugin " + pluginTypeId + " provider " + providerId,`,
  );
  lines.push(`    );`);
  lines.push(`  }`);
  lines.push(
    `  const companion = OAUTH_COMPANION_SCOPES_BY_PROVIDER[providerId] ?? [];`,
  );
  lines.push(`  return [...companion, ...pluginScopes].join(" ");`);
  lines.push(`}`);
  lines.push(``);

  fs.mkdirSync(path.dirname(registryOutPath), { recursive: true });
  fs.writeFileSync(registryOutPath, lines.join("\n") + "\n", "utf8");

  console.log(
    `extract-plugin-oauth-registry: wrote ${path.relative(repoRoot, registryOutPath)}`,
  );

  if (pluginIds.length === 0) {
    throw new Error(
      "extract-plugin-oauth-registry: no plugin manifests with contributions.oauth — expected at least one",
    );
  }
}

async function main(): Promise<void> {
  emitRegistry(await collectFromManifests());
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
